//登录
export const LOGIN_CHANGE = 'LOGIN_CHANGE';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
//登录验证
export const LOGIN_FIRST = 'LOGIN_FIRST';
export const FETCH_USERINFO_REQUEST = 'FETCH_USERINFO_REQUEST';
export const FETCH_USERINFO_SUCCESS = 'FETCH_USERINFO_SUCCESS';
export const FETCH_USERINFO_FAILURE = 'FETCH_USERINFO_FAILURE';
//用户注册
export const ERROR_MASSAGE = 'ERROR_MASSAGE';
export const REGISTER_CHANGE = 'REGISTER_CHANGE';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const LOGOUT = 'LOGOUT';
//用户
export const ADD_USER = 'ADD_USER';
export const REMOVE_USER = 'REMOVE_USER';
//用户公开信息
export const BOSS_CHANGE = 'BOSS_CHANGE';
export const GENUIS_CHANGE = 'GENUIS_CHANGE';
//用户更新
export const AUTH_SUCCESS = 'AUTH_SUCCESS';